server:
  port: 8082
  servlet:
    context-path: /api/v1
  tomcat:
    connection-timeout: -1
springdoc:
  swagger-ui:
    path: /docs-mcprepo
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    url: ${MAIN_DB_PROD_URL}
    username: ${MAIN_DB_PROD_ID}
    password: ${MAIN_DB_PROD_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      platform: mysql
      encoding: UTF-8
      data-locations: classpath:data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_PROD_HOST}
      port: ${REDIS_PROD_PORT}

# GitHub API 설정
github:
  api:
    url: https://api.github.com
    token: ${GITHUB_API_TOKEN_PROD:}

# Anthropic API 설정
anthropic:
  api:
    url: https://api.anthropic.com
    key: ${ANTHROPIC_API_KEY_PROD:}
    model: claude-3-sonnet-20240229
    max-tokens: 4000

# JWT 설정
jwt:
  secret: ${JWT_SECRET_PROD:}
  token-validity-in-seconds: ${JWT_EXPIRATION:86400}

# 로깅 설정
logging:
  level:
    com.miraclestudio.mcpreposerver: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
  # 로그 파일 경로 및 보존 설정
  file:
    name: ${LOG_PATH:/var/log/mcpreposerver}/mcpreposerver.log
  config: classpath:logback-spring.xml

# 로그 파일 관리 설정
log:
  path: ${LOG_PATH:/var/log/mcpreposerver}
  error:
    retention-days: 7 # 프로덕션 환경에서는 에러 로그를 30일간 보존
  retention-days: 30 # 프로덕션 환경에서는 일반 로그를 90일간 보존

app:
  oauth2:
    authorized-redirect-uris: ${OAUTH2_AUTHORIZED_REDIRECT_URIS_PROD}
    default-success-url: ${OAUTH2_DEFAULT_SUCCESS_URL_PROD}
    failure-redirect-url: ${OAUTH2_FAILURE_REDIRECT_URL_PROD}