
server:
  port: 8082
  tomcat:
    connection-timeout: -1
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    url: ${MAIN_DB_PROD_URL}
    username: ${MAIN_DB_PROD_ID}
    password: ${MAIN_DB_PROD_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_ID}
          github:
            client-id: ${GITHUB_OAUTH2_ID}

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_PROD_HOST}
      port: ${REDIS_PROD_PORT}